site_name: Setup Wiki
theme:
    name: 'material'
    palette:
        primary: 'indigo'
        accent: 'pink'
    logo:
        icon: 'receipt'
    favicon: 'assets/images/favicon.ico'
pages:
    - Main Page: 'index.md'
    - Backup:
        - 'Borg': 'Backup/Borg.md'
    - Raspberry Pi:
        - 'Headless Setup': 'Raspberry_Pi/Headless_Setup.md'
        - 'OpenVPN': 'Raspberry_Pi/OpenVPN.md'
    - Troubleshooting:
        - 'Manjaro': 'Troubleshooting/Manjaro.md'
        - 'Arduino': 'Troubleshooting/Arduino.md'
    - Miscellaneous:
        - 'Dotfiles': 'Miscellaneous/Dotfiles.md'
        - 'LUKS Disk Encryption': 'Miscellaneous/LUKS_Disk_Encryption.md'
repo_name: 'rngcntr/setupwiki'
repo_url: 'https://github.com/rngcntr/setupwiki'
edit_uri: ''
use_directory_urls: False
extra:
    social:
        - type: 'github'
          link: 'https://github.com/rngcntr'
        - type: 'twitter'
          link: 'https://twitter.com/rngcntr'
markdown_extensions:
    - admonition
    - markdown.extensions.admonition
    - codehilite:
        linenums: true
    - markdown.extensions.codehilite:
        guess_lang: true
    - markdown.extensions.def_list
    - markdown.extensions.footnotes
    - markdown.extensions.meta
    - markdown.extensions.toc:
        permalink: true
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.magiclink:
        repo_url_shorthand: true
        user: squidfunk
        repo: mkdocs-material
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
